remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false
title: Toni's MMC License
description: Custom license for Minecraft mod authors.
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
